config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :record_types

  get 'welcome/index'
  root 'welcome#index'
  
  resources :account_records

end

app/models/account_record.rb
class AccountRecord < ActiveRecord::Base
  belongs_to :user
  belongs_to :record_type
  #has_one :record_type

  validates_presence_of :record_type_id, :amounts
  with_options :allow_blank => true do |v|
    v.validates_numericality_of :amounts
  end

  #scope :join_record_type, lambda { joins(:record_type) }
  scope :include_record_type, lambda { includes(:record_type) }
  #scope :join_record_type, lambda { joins('LEFT OUTER JOIN record_types ON account_records.record_type_id = record_types.id') }

  scope :incomings, lambda { where(:incoming_or_outgoing => 1) }
  scope :outgoings, lambda { where(:incoming_or_outgoing => -1) }
  
  scope :date_range, lambda { |time_start, time_end| 
    where(
      :occur_date => ( time_start.strftime("%Y-%m-%d")..(time_end + 1.day).strftime("%Y-%m-%d") )
    )
  }
  
  scope :sorted, lambda { order("#{table_name}.occur_date DESC")}
end

app/models/record_type.rb
class RecordType < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user
  #belongs_to :account_record
  has_many :account_record
  
  scope :sorted, lambda { order("#{table_name}.updated_at DESC") }
  scope :title_exist, lambda { |title| where(:title => title) }

  def self.create(title, user_id)
    record_type = RecordType.new
    record_type.title = title
    record_type.user_id = user_id
    record_type.save
    return record_type
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :account_records
  has_many :record_types
end

app/controllers/account_records_controller.rb
class AccountRecordsController < ApplicationController

  before_filter :set_time, :only => [:index, :new]
  before_filter :set_account_record, :only => [:edit, :update, :show, :destroy]
  before_filter :authenticate_user!

  def index
    if params['account_records_date_start'] or params['account_record_date_end']
      begin
        @time_start = DateTime.parse(params['account_records_date_start'])
      rescue
        @time_start = DateTime.now
      end
      begin
        @time_end = DateTime.parse(params['account_records_date_end'])
      rescue
        @time_end = DateTime.now
      end
    else
      @time_start, @time_end = @time, @time
    end
    @account_records = current_user.account_records.include_record_type.date_range(@time_start, @time_end).sorted
    @incoming_records = current_user.account_records.include_record_type.incomings.date_range(@time_start, @time_end).sorted
    @outgoing_records = current_user.account_records.include_record_type.outgoings.date_range(@time_start, @time_end).sorted
  end

  def new
    @account_record = AccountRecord.new
    @record_types = current_user.record_types.all.sorted
    @record_type = @record_types.first
  end

  def create
    @record_type_id = params['account_record']['record_type']
    @record_type_title = params['account_record']['record_type_title'].strip

    @account_record = AccountRecord.new(account_record_params)
    @account_record.user_id = current_user.id
    @record_type = RecordType.find(@record_type_id)
    if @record_type.blank? || @record_type.title != @record_type_title
      @record_type = RecordType.where(:title => @record_type_title).first
      @record_type = RecordType.create(@record_type_title, current_user.id) if @record_type.blank?
    end
    @account_record.record_type_id = @record_type.id
    
    if @account_record.save
      redirect_to account_records_path
    else
      render :new
    end
  end

  def edit
    @record_types = current_user.record_types.all.sorted
    @record_type = RecordType.find(@account_record.record_type)
  end

  def update
    if @account_record.update(account_record_params)
      redirect_to @account_record, :notice => 'AccountRecord update successfully'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @account_record.destroy
    redirect_to account_records_url, :notice => "删除成功"
  end

  private
  def account_record_params
    params.require(:account_record).permit(:amounts, :occur_date, :incoming_or_outgoing, :description)
  end
  def set_time
    @time = DateTime.now
  end
  def set_account_record
    @account_record = AccountRecord.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/record_types_controller.rb
class RecordTypesController < ApplicationController
  before_action :set_record_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /record_types
  # GET /record_types.json
  def index
    @record_types = current_user.record_types.all.sorted
  end

  # GET /record_types/1
  # GET /record_types/1.json
  def show
  end

  # GET /record_types/new
  def new
    @record_type = RecordType.new
  end

  # GET /record_types/1/edit
  def edit
  end

  # POST /record_types
  # POST /record_types.json
  def create
    @record_type = RecordType.new(record_type_params)
    @record_type.user_id = current_user.id
    respond_to do |format|
      if @record_type.save
        format.html { redirect_to @record_type, notice: 'Record type was successfully created.' }
        format.json { render :show, status: :created, location: @record_type }
      else
        format.html { render :new }
        format.json { render json: @record_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /record_types/1
  # PATCH/PUT /record_types/1.json
  def update
    respond_to do |format|
      if @record_type.update(record_type_params)
        format.html { redirect_to @record_type, notice: 'Record type was successfully updated.' }
        format.json { render :show, status: :ok, location: @record_type }
      else
        format.html { render :edit }
        format.json { render json: @record_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /record_types/1
  # DELETE /record_types/1.json
  def destroy
    @record_type.destroy
    respond_to do |format|
      format.html { redirect_to record_types_url, notice: 'Record type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record_type
      @record_type = RecordType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_type_params
      params.require(:record_type).permit(:title, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def update
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  
  end
end

app/helpers/account_records_helper.rb
module AccountRecordsHelper
  def aggregate(account_records)
    sum = 0
    if !account_records.nil?
      account_records.each do |ar|
        sum += ar.incoming_or_outgoing * ar.amounts
      end
    end
    number_to_currency sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_bootstrap_class(level)
    case level.to_sym
    when :success then "alert alert-success"
    when :notice then "alert alert-info"
    when :alert then "alert alert-danger"
    when :error then "alert alert-danger"
    end
  end
end

app/helpers/record_types_helper.rb
module RecordTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/account_records/_detail_list.html.erb
<% if !account_records.nil? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>合计</th>
        <th></th>
        <th><%= aggregate(account_records) %></th>
      </tr>
    </thead>
    <tbody>
    <% account_records.each do |account_record| -%>
      <%= render :partial => 'entry', :locals => {:entry => account_record} %>  
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/account_records/_entry.html.erb
<tr>
  <td><%= entry.record_type.title %></td>
  <td><%= l entry.occur_date %></td>
  <td><%= number_to_currency entry.amounts*entry.incoming_or_outgoing %></td>
  <td><%= link_to '编辑', edit_account_record_path(entry) %></td>
  <td><%= link_to '删除', entry, :method => :delete, :data => {:confirm => '确定?'} %></td>
</tr>

app/views/account_records/_form.html.erb
<div class="row">
  <%= form_for(@account_record, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
    <% if @account_record.errors.any? %>
      <div id="error_explanation" class="col-sm-6 col-sm-offset-3">
        <h2><%= pluralize(@account_record.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @account_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :occur_date, :class => "control-label col-sm-1 col-sm-offset-3" %>
      <div class="col-sm-5">
        <div class="input-group date" id="datetimepicker">
          <%= f.text_field :occur_date, :class => "form-control", :placeholder => '日期', :required => true %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $(function() {
        $('#datetimepicker').datetimepicker({
          defaultDate: moment().format('YYYY-MM-DD H:mm:ss'),
          format: "YYYY-MM-DD H:mm:ss",
          locale: 'zh-cn'
        });
      });
    </script>
    <div class="form-group">
      <%= f.label :amounts, :class => "control-label col-sm-1 col-sm-offset-3" %>
      <div class="col-sm-5">
        <%= f.text_field :amounts, :class => "form-control", :placeholder => '金额', :required => true, :pattern => '^([1-9][\d]{0,7}|0)(\.[\d]{1,2})?$' %>
      </div>
    </div>
    <div class="form-group">
      <div class="radio col-sm-2 col-sm-offset-4">
        <%= f.label :incoming_or_outgoing, :class => "checkbox-inline" do %>
          <%= f.radio_button :incoming_or_outgoing, -1, :checked => true %><%= I18n.t(:outgoing) %>
        <% end %>
      </div>
      <div class="radio col-sm-2 col-sm-offset-2">
        <%= f.label :incoming_or_outgoing, :class => "checkbox-inline" do %>
          <%= f.radio_button :incoming_or_outgoing, 1 %><%= I18n.t(:incoming) %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :record_type, :class => "control-label col-sm-1 col-sm-offset-3" %>
      <div class="col-sm-5">
        <div class="input-group">
            <%= f.hidden_field :record_type, :value => "#{@record_type.blank? ? '' : @record_type.id}" %>
            <% @record_types.each do |record_type| %>
              <button type="button" class="btn btn-default <%= "active" if record_type.id == (@record_type.blank? ? @record_types.first.id : @record_type.id) %>" 
                name="<%= record_type.id %>" onclick="set_record_type(<%= record_type.id %>, '<%= record_type.title %>')">
                <%= record_type.title %>
              </button>
            <% end %>
            <span class="input-group-addon">
              <%= link_to new_record_type_path do%>
                <span class="glyphicon glyphicon-plus"></span>
              <% end %>
            </span>
        </div>
        <%= f.text_field :record_type_title, :class => "form-control", :placeholder => '类型', :required => true, 
          :value => "#{@record_type.blank? ? '' : @record_type.title}" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => "control-label col-sm-1 col-sm-offset-3" %>
      <div class="col-sm-5">
        <%= f.text_area :description, :class => "form-control", :placeholder => "备注" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-1 col-sm-offset-8">
        <%= f.submit :class => "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>
<script type="text/javascript">
  function set_record_type(id, title){
    $("input[name='account_record[record_type]'").val(id);
    $("input[name='account_record[record_type_title]'").val(title);
    $('.btn.btn-default.active').removeClass('active');
    $("button[name='" + id + "']").addClass('active');
  }
</script>

app/views/account_records/edit.html.erb
<div class="panel panel-default">
  <%= render :partial => 'shared/panel_heading', :locals => {:title => '修改'} %>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/account_records/index.html.erb
<div class="panel panel-default">
  <%= render :partial => 'shared/panel_heading', :locals => {:title => '明细'} %>
  <div class="panel-body">
    <div class="row">
      <%= form_tag account_records_path, :id => "account_records_date_form", :method => 'get',
                                          :class => "form-horizontal", :role => "form" do %>
        <div class="form-group col-sm-offset-3">
          <label for="account_records_date_start" class="control-label col-sm-2 col-sm-offset-3">开始日期</label>
          <div class="col-sm-2">
            <div class="input-group date" id="datetimepicker-start">
              <%= text_field_tag :account_records_date_start, "#{@time_start.strftime('%Y-%m-%d')}", :class => "form-control span2" %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="account_records_date_end" class="control-label col-sm-2 col-sm-offset-3">结束日期</label>
          <div class="col-sm-2">
            <div class="input-group date" id="datetimepicker-end">
              <%= text_field_tag :account_records_date_end, "#{@time_end.strftime('%Y-%m-%d')}", :class => "form-control" %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
        <script type="text/javascript">
          $(function() {
            $('#datetimepicker-start').datetimepicker({
              format: "YYYY-MM-DD",
              locale: 'zh-cn'
            });
            $('#datetimepicker-end').datetimepicker({
              format: "YYYY-MM-DD",
              locale: 'zh-cn'
            });
            $('#datetimepicker-start').on("dp.change", function(e){
              $('#account_records_date_form').submit();
            });
            $('#datetimepicker-end').on("dp.change", function(e){
              $('#account_records_date_form').submit();
            });
          });
        </script>
      <% end %>
    </div>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <ul id="listTab" class="nav nav-tabs nav-justified">
          <li class="active"><a href="#aggregateTab" data-toggle="tab">全部</a></li>
          <li><a href="#outgoingTab" data-toggle="tab">支出</a></li>
          <li><a href="#incomingTab" data-toggle="tab">收入</a></li>
        </ul>
        <div id="listTabContent" class="tab-content">
          <div class="tab-pane fade in active" id="aggregateTab">
            <%= render :partial => 'detail_list', :locals => {:account_records => @account_records} %>  
          </div>
          <div class="tab-pane fade" id="outgoingTab">
            <%= render :partial => 'detail_list', :locals => {:account_records => @outgoing_records} %>  
          </div>
          <div class="tab-pane fade" id="incomingTab">
            <%= render :partial => 'detail_list', :locals => {:account_records => @incoming_records} %>  
          </div>
        </div>
      </p>
    </div>
  </div>
</div>

app/views/account_records/new.html.erb
<div class="panel panel-default">
  <%= render :partial => 'shared/panel_heading', :locals => {:title => '记账'} %>
  <div class="panel-body">
    <h1 class="text-center"><%= "#{@time.year}年#{@time.month}月#{@time.day}日  " + t(:date)[:day_names][@time.wday % 7] %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/account_records/show.html.erb
<h1>AccountRecords#show</h1>
<p>Find me in app/views/account_records/show.html.erb</p>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_bootstrap_class(key) %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
      &times;
    </button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <%= link_to root_path, :class => "navbar-brand" do %>
      <%= t(:label_book_keeper) %>
    <% end %>
  </div>
  <div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <%= link_to "#", :class => "dropdown-toggler", :data => {:toggle => "dropdown", :target => "#"} do %>
          记账
          <span class="caret"></span>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to '记一笔', new_account_record_path %></li>
          <li><%= link_to '明细', account_records_path %></li>
          <li><%= link_to '报表', account_records_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Java 
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">jmeter</a></li>
          <li><a href="#">EJB</a></li>
          <li><a href="#">Jasper Report</a></li>
          <li class="divider"></li>
          <li><a href="#">分离的链接</a></li>
          <li class="divider"></li>
          <li><a href="#">另一个分离的链接</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <%= link_to "#", :class => "dropdown-toggler", :data => {:toggle => "dropdown", :target => "#"} do %>
          用户中心
          <span class="caret"></span>
        <% end %>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= link_to '个人中心', edit_user_registration_path %></li>
            <li><%= link_to '注销', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to '注册', new_user_registration_path %></li>
            <li><%= link_to '登录', new_user_session_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(:label_book_keeper) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= yield :header_tags %>
</head>
<body>

  <%= render 'layouts/nav' %>
  <%= render 'layouts/flash' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/record_types/_form.html.erb
<div class="row">
  <%= form_for(@record_type, :html => {:class => "form-horizontal", :role => "form", :multipart => true}) do |f| %>
    <% if @record_type.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@record_type.errors.count, "error") %> prohibited this record_type from being saved:</h2>

        <ul>
        <% @record_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, :class => "control-label col-sm-1 col-sm-offset-3" %>
      <div class="col-sm-5">
        <%= f.text_field :title, :class => "form-control", :placeholder => '名称', :required => true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :image, :class => "control-label col-sm-1 col-sm-offset-3" %>
      <div class="col-sm-5">
        <%= f.file_field :image, :class => "form-control", :placeholder => '文件名', :required => true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-7">
        <%= f.submit :class => "form-control" %>
      </div>
    </div>
  <% end %>
</div>

<input id="fileupload" type="file" multiple/>
<script type="text/javascript">
  $("#fileupload").fileupload();
</script>

app/views/record_types/edit.html.erb
<h1>Editing record_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @record_type %> |
<%= link_to 'Back', record_types_path %>

app/views/record_types/index.html.erb
<h1>Listing record_types</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @record_types.each do |record_type| %>
      <tr>
        <td><%= record_type.title %></td>
        <td><%= image_tag record_type.image.url(:thumb) %></td>
        <td><%= link_to 'Show', record_type %></td>
        <td><%= link_to 'Edit', edit_record_type_path(record_type) %></td>
        <td><%= link_to 'Destroy', record_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record type', new_record_type_path %>

app/views/record_types/new.html.erb
<div class="panel panel-default">
  <%= render :partial => 'shared/panel_heading', :locals => {:title => t(:new_record_type)} %>
  <div class="panel-body">
    <%= render 'form' %>
    <%= link_to t(:record_types), record_types_path %>
  </div>
</div>

app/views/record_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record_type.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @record_type.image.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_record_type_path(@record_type) %> |
<%= link_to 'Back', record_types_path %>

app/views/shared/_panel_heading.html.erb
<div class="panel-heading center">
  <%= title %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<h1>欢迎回来<%= ", #{@user.name}" if @user %></h1>